--- 
- name: Установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка и настройка проксирующего nginx
  hosts: vm_1
  roles: 
    - role: nginx_proxy
  tags:
    - install_proxy_nginx

- name: Установка и настройка nginx с кастомной страницей
  hosts: vm_2
  roles: 
    - role: nginx_custom
  tags:
    - install_custom_nginx

